services:
    webserver:
        image: nginx:latest
        ports:
            - '8080:80'
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

    assets:
        image: scheb42/stock-panel-assets
        build:
            dockerfile: Dockerfile
            target: frontend-deployment
            context: .

    php-fpm:
        image: scheb42/stock-panel-php
        build:
            dockerfile: Dockerfile
            target: backend-deployment
            context: .
        volumes:
            - ./.env.local:/application/.env:ro
            - ./var/data.db:/application/var/data.db
