name: "CI"

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    - image: scheb42/stock-panel-assets
                      target: frontend-deployment
                    - image: scheb42/stock-panel-php
                      target: backend-deployment
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                if: ${{ github.ref_name == 'main' }}
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ matrix.image }}
                    tags: |
                        type=sha
                        type=ref,event=branch
                        type=ref,event=pr
                        # set latest tag for default branch
                        type=raw,value=latest,enable={{ is_default_branch }}

            -   name: Build and push
                uses: docker/build-push-action@v5
                with:
                    context: .
                    file: ./Dockerfile
                    target: ${{ matrix.target }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    push: ${{ github.ref_name == 'main' }}
